<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>user_name</name>
   <tag></tag>
   <elementGuidId>5d22a8d3-568a-452e-b8ae-465afa6c6899</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_desktop_user_info']/div/a[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.hidden-sm-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>44d115bd-c3b4-486b-8033-59ed95185aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden-sm-down</value>
      <webElementGuid>a10be3c9-9a72-4866-9825-e11d414f2e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tilapia TheFish</value>
      <webElementGuid>0a12a491-7e29-483a-af7e-2a2f25f63525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_desktop_user_info&quot;)/div[@class=&quot;user-info&quot;]/a[@class=&quot;account&quot;]/span[@class=&quot;hidden-sm-down&quot;]</value>
      <webElementGuid>68dda751-9df2-4eb0-8820-251b2dc173db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_desktop_user_info']/div/a[2]/span</value>
      <webElementGuid>dd35e27c-80aa-4fd9-acc6-c0a6011bbaa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>f53e1170-daa1-4210-9ff6-5097211d0906</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
