<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_optin</name>
   <tag></tag>
   <elementGuidId>272f45a2-7ebe-4b32-acbd-207870903e76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='optin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;optin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61d849e3-e406-4609-8df2-f5c93813653b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optin</value>
      <webElementGuid>2ead2b0a-025b-4f3a-a57b-da34c97c09f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e22760c2-8944-4a8a-b214-91d3b6b852bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5c8547e2-5e7d-454d-a27a-9355330c5a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-form&quot;)/div[1]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-6&quot;]/span[@class=&quot;custom-checkbox&quot;]/label[1]/input[1]</value>
      <webElementGuid>6c727aea-a3b2-4ab3-8de2-cfba4c77ba82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='optin']</value>
      <webElementGuid>0a0d9187-2e5a-47b0-9abf-3a12f0c59c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer-form']/div/div[7]/div/span/label/input</value>
      <webElementGuid>57509d2d-1971-43f6-864f-ca8dafb56b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>bef63046-ddf8-4304-9b4d-e87bb650f6e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'optin' and @type = 'checkbox']</value>
      <webElementGuid>2da86402-5ef9-4246-a3d9-6318121eb489</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
