<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_newsletter</name>
   <tag></tag>
   <elementGuidId>c2fe21f2-b626-4aa0-8aa6-9146a567c112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='newsletter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;newsletter&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b802dd0f-4074-4e50-a378-1e5825052283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newsletter</value>
      <webElementGuid>196f1566-21f4-4cd1-b504-7c365eee688a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3c30d06a-f67d-4bea-8089-0de294c75622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7c4db39b-201a-42e5-a72b-5d6d3b48b761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-form&quot;)/div[1]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-6&quot;]/span[@class=&quot;custom-checkbox&quot;]/label[1]/input[1]</value>
      <webElementGuid>3b09b3c5-9116-4f66-9c96-8aaa71732a12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='newsletter']</value>
      <webElementGuid>b26724e8-a2c0-4928-afff-8aa622905395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer-form']/div/div[9]/div/span/label/input</value>
      <webElementGuid>22792953-73ce-4f6e-a5b0-815758ab0c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/span/label/input</value>
      <webElementGuid>7486e867-060b-42a4-9b1b-bed258d04244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'newsletter' and @type = 'checkbox']</value>
      <webElementGuid>113f252a-8506-4339-b0eb-b048f06327e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
