<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Customers</name>
   <tag></tag>
   <elementGuidId>8fe29543-4100-4aed-9e13-070a0ac3cbcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='subtab-AdminCustomers']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subtab-AdminCustomers > a.link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a1618f0f-5898-42b6-855c-764dfb242c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/administration/index.php/sell/customers/?_token=Fi12ridPDPsCjOZDkDrlOsRpyFjmF9GQYYai8-PtYLM</value>
      <webElementGuid>4f8becae-7659-484d-8ff1-b6c68875cc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>781931ad-600f-454e-b438-ca372c1be5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Customers                              </value>
      <webElementGuid>c3ec26d4-bfca-4ffb-aeb9-415069260a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtab-AdminCustomers&quot;)/a[@class=&quot;link&quot;]</value>
      <webElementGuid>75e12386-f224-4ee1-a494-f7f7ceec8961</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='subtab-AdminCustomers']/a</value>
      <webElementGuid>d04796f8-89f5-4280-9b42-9a2062bec3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Customers')]</value>
      <webElementGuid>15e4e47c-7614-432b-aecf-f7d31dd9e263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/administration/index.php/sell/customers/?_token=Fi12ridPDPsCjOZDkDrlOsRpyFjmF9GQYYai8-PtYLM')]</value>
      <webElementGuid>3f926d78-8419-4361-be4c-7eea4ab8408c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a</value>
      <webElementGuid>ce251f58-39a4-48dc-af9c-f6949bc0f34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/administration/index.php/sell/customers/?_token=Fi12ridPDPsCjOZDkDrlOsRpyFjmF9GQYYai8-PtYLM' and (text() = '
                                Customers                              ' or . = '
                                Customers                              ')]</value>
      <webElementGuid>34530af6-9bf9-448d-8f89-935ef5f656d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/administration/index.php/sell/customers/?_token=KNqbHN3eXeSql0yO1by9XK_RO5LyckhYkkLavllevBA')]</value>
      <webElementGuid>709593a6-1f27-4431-99f7-328f84c895d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/administration/index.php/sell/customers/?_token=KNqbHN3eXeSql0yO1by9XK_RO5LyckhYkkLavllevBA' and (text() = '
                                Customers                              ' or . = '
                                Customers                              ')]</value>
      <webElementGuid>be3630ff-eae1-49fb-8072-57798b280c2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
