<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Customers</name>
   <tag></tag>
   <elementGuidId>043cef94-0459-4aac-b3b3-07b2dda4e656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='subtab-AdminParentCustomer']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subtab-AdminParentCustomer > a.link > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31da6642-32dc-4fcd-ab6e-c344f7275fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Customers                      </value>
      <webElementGuid>1039e7e4-daae-45c1-b1ae-4c818222854a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtab-AdminParentCustomer&quot;)/a[@class=&quot;link&quot;]/span[1]</value>
      <webElementGuid>714b4b32-773a-44b0-b1de-82b8fb745fe2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='subtab-AdminParentCustomer']/a/span</value>
      <webElementGuid>9d5fb82e-66a1-4e48-a7fb-6d36f79690cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span</value>
      <webElementGuid>8deafb77-1765-429d-8d4e-3c5748fccb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                        Customers                      ' or . = '
                        Customers                      ')]</value>
      <webElementGuid>4d84bd3d-75bf-4e67-ab61-7c9b7fbe6160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
