<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_btn btn-link dropdown-toggle dropdown-tog_b028f2</name>
   <tag></tag>
   <elementGuidId>c92e88a5-691b-4f5e-a154-6d7e2f153ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='customer_grid_table']/tbody/tr/td[13]/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-link.dropdown-toggle.dropdown-toggle-dots.dropdown-toggle-split.no-rotate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96a52ee8-7c4c-4522-b1f4-4abab6975996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link dropdown-toggle dropdown-toggle-dots dropdown-toggle-split no-rotate</value>
      <webElementGuid>55feda90-335c-402d-bf11-94b1b79a6995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>ce86347c-8349-4922-a81a-855d134b0faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72c574d4-78e4-4c23-9a11-82474880c431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bd5b7c3a-816e-4c03-9a55-30090f3686e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_grid_table&quot;)/tbody[1]/tr[1]/td[@class=&quot;action-type column-actions&quot;]/div[@class=&quot;btn-group-action text-right&quot;]/div[@class=&quot;btn-group&quot;]/a[@class=&quot;btn btn-link dropdown-toggle dropdown-toggle-dots dropdown-toggle-split no-rotate&quot;]</value>
      <webElementGuid>ed9e6cc4-b424-4a5f-891a-b939b9891cdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='customer_grid_table']/tbody/tr/td[13]/div/div/a[2]</value>
      <webElementGuid>a26b369b-dc88-4e74-83d6-dbf7d76fdff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/div/div/a[2]</value>
      <webElementGuid>1c576135-1a9f-4e9a-be11-f90d289a34dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
