<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_delete        Supprimer</name>
   <tag></tag>
   <elementGuidId>5f8a9b37-da99-4e3f-a108-ada09a999171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='customer_grid_table']/tbody/tr/td[13]/div/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.tooltip-link.js-delete-customer-row-action.dropdown-item.grid-supprimer-row-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb727c9a-7491-4832-8de2-401a5b990f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn tooltip-link js-delete-customer-row-action dropdown-item grid-supprimer-row-link</value>
      <webElementGuid>ece84719-ad61-48c4-8af4-a34b003c8160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4b9e5c79-5321-4237-bbe4-e0347d5f9265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-customer-id</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>c37d6c9e-0c9d-4821-a22e-6b3c28dae568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-customer-delete-url</name>
      <type>Main</type>
      <value>/administration/index.php/sell/customers/delete?_token=Fi12ridPDPsCjOZDkDrlOsRpyFjmF9GQYYai8-PtYLM</value>
      <webElementGuid>f6f00643-39a6-4ee3-9e40-d13da0856ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      delete
        Supprimer
  </value>
      <webElementGuid>ae3bb43e-4175-4b9c-bf56-45b54fed5802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_grid_table&quot;)/tbody[1]/tr[1]/td[@class=&quot;action-type column-actions&quot;]/div[@class=&quot;btn-group-action text-right&quot;]/div[@class=&quot;btn-group show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right show&quot;]/a[@class=&quot;btn tooltip-link js-delete-customer-row-action dropdown-item grid-supprimer-row-link&quot;]</value>
      <webElementGuid>c394bbd5-a760-4547-95bf-f8a2d7d1dd45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='customer_grid_table']/tbody/tr/td[13]/div/div/div/a[2]</value>
      <webElementGuid>0e14696f-2bb7-4283-970a-e7fd62275aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[17]</value>
      <webElementGuid>76249e1f-fc3e-46a5-b814-afacc0fb5abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/div/div/div/a[2]</value>
      <webElementGuid>0686b41e-cf3a-4e2c-a9f1-73011d25f21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
      delete
        Supprimer
  ' or . = '
      delete
        Supprimer
  ')]</value>
      <webElementGuid>495ade67-8eb5-4155-bf64-050b5dda716c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
