<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_customer_customers_bulk</name>
   <tag></tag>
   <elementGuidId>a6b90523-7d78-4a91-9899-da46ae613a81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='customer_customers_bulk[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;customer_customers_bulk[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99ed0c6b-4214-40ec-b6dc-98b6ee759a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>244c7631-23ef-419c-abef-d527b91d6f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-bulk-action-checkbox</value>
      <webElementGuid>1f56c540-9930-4d68-a06b-04e33ea6c7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_customers_bulk[]</value>
      <webElementGuid>ea032613-e735-4772-88f4-bc8abba4036c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>b78a2599-1fc4-4562-8872-6eecca79a6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_grid_table&quot;)/tbody[1]/tr[1]/td[@class=&quot;bulk_action-type column-customers_bulk&quot;]/div[@class=&quot;md-checkbox&quot;]/label[1]/input[@class=&quot;js-bulk-action-checkbox&quot;]</value>
      <webElementGuid>2d884c08-1fad-4435-8a71-3bde387aaf46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='customer_customers_bulk[]']</value>
      <webElementGuid>888de533-a00e-4d7b-b4a8-12bb433aca0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='customer_grid_table']/tbody/tr/td/div/label/input</value>
      <webElementGuid>5af955e3-de0a-4470-841d-7a3abdcee710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td/div/label/input</value>
      <webElementGuid>8d838a06-3b1d-4417-b3cf-572280464a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'customer_customers_bulk[]']</value>
      <webElementGuid>9779558e-5c3d-4636-9c1f-e06440a667c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
