<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Customers</name>
   <tag></tag>
   <elementGuidId>97aa039d-2bda-4c45-ace2-557e7d649d21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='subtab-AdminCustomers']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subtab-AdminCustomers > a.link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a600564-d589-4089-bf42-cb87c95da69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/administration/index.php/sell/customers/?_token=KNqbHN3eXeSql0yO1by9XK_RO5LyckhYkkLavllevBA</value>
      <webElementGuid>7f061381-e656-4c6c-9e60-40a89d2e560f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>18fb4154-f878-4778-909f-4b41647de935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Customers
                                </value>
      <webElementGuid>1ffcbebc-4638-4469-ad1f-69c6e1276f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtab-AdminCustomers&quot;)/a[@class=&quot;link&quot;]</value>
      <webElementGuid>b6a085c8-d345-431b-af7c-12a13229fe87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='subtab-AdminCustomers']/a</value>
      <webElementGuid>57a67f35-297e-4a18-a315-f8915b67ba85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Customers')]</value>
      <webElementGuid>47bf98c2-a853-4d65-9002-b2ccf9912193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/administration/index.php/sell/customers/?_token=KNqbHN3eXeSql0yO1by9XK_RO5LyckhYkkLavllevBA')])[2]</value>
      <webElementGuid>5de4b171-bb5a-46a7-92f0-c7831b32a7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a</value>
      <webElementGuid>5e5b911c-9b48-428b-bfc7-0ed265b84621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/administration/index.php/sell/customers/?_token=KNqbHN3eXeSql0yO1by9XK_RO5LyckhYkkLavllevBA' and (text() = ' Customers
                                ' or . = ' Customers
                                ')]</value>
      <webElementGuid>2c109d7d-4020-4644-8332-a4c90c42c532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
